name = "Icepack"
author = "Vinicius Santos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "faf27752c3f39f9eb347bdcf0734e89823b5aa4ce476e9ee135ed985a6e65e57"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
