name = "Icepack"
author = "Vinicius"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83078aeed346369fc82838f3844586a89ef562b3140da6281a8ca7341cd46050"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
