name = "Icepack"
author = "Vinicius Santos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "818862093bfdd6bfe2d62ddf331fbfee6212c8d79c288349df8939cd85626146"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
