name = "Icepack"
author = "Vinicius Santos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5915c81e0e68c04cd5c924fe1741a724237888cbac2df535ae7ad17a2fc108df"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
