name = "Icepack"
author = "Vinicius Santos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14041104baf7e6f41c35e66679ed2795431e9f485bc8b94602c2052590387f59"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
