name = "Icepack"
author = "Vinicius Santos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2ed4476edf9fbfdea34f5128aaa06d190aae9380e2b4f7415235ac0886907d6"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
