name = "Icepack"
author = "Vinicius"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a69ca573ce1a74cc31e8aadac09370630de9716421c1700723c841320e9e9ec"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
